"""Snapshot live content back into the repo as committable SQL.

Content used to be seeded by migration, which made the repo the record of what
production holds. Editing rows directly breaks that, so the repo keeps a
generated snapshot instead: history, review if you want it, and a rebuild path
if the project is ever restored from scratch.

The generated files are `delete`-then-`insert` for exactly the rows they
contain, which is the same shape as the seed migrations they replace.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import db
from .config import REPO_ROOT

SEED_DIR = REPO_ROOT / "mobile" / "supabase" / "seeds" / "content"


def sql_literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, list):
        if not value:
            return "'{}'::text[]"
        if all(isinstance(v, str) for v in value):
            # Each element is double-quoted so a comma, brace or space inside a
            # tag cannot break out of the array literal.
            quoted = [
                '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"' for v in value
            ]
            return "'{" + ",".join(quoted).replace("'", "''") + "}'::text[]"
        return "'" + json.dumps(value).replace("'", "''") + "'::jsonb"
    if isinstance(value, dict):
        return "'" + json.dumps(value).replace("'", "''") + "'::jsonb"
    return "'" + str(value).replace("'", "''") + "'"


def insert_statements(table: str, rows: list[dict[str, Any]], columns: list[str]) -> str:
    if not rows:
        return f"-- no rows in {table}\n"
    lines = [f"insert into {table}\n  ({', '.join(columns)})\nvalues"]
    values = [
        "  (" + ", ".join(sql_literal(row.get(column)) for column in columns) + ")" for row in rows
    ]
    lines.append(",\n".join(values) + ";")
    return "\n".join(lines) + "\n"


def _header(title: str) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f"-- {title}\n"
        f"-- GENERATED by tools/admin — do not hand-edit; edit in the admin console\n"
        f"-- and export again. Snapshot taken {stamp}.\n"
        f"--\n"
        f"-- This is a record of what production holds, not a migration to run\n"
        f"-- blindly: it deletes and reinserts every row it contains.\n\n"
        f"begin;\n\n"
    )


def export_recipes() -> Path:
    recipes = db.select("recipes", order="collection,sort_order,id")
    ingredients = db.select("recipe_ingredients", order="recipe_id,position")
    steps = db.select("recipe_steps", order="recipe_id,position")

    recipe_columns = [
        "id", "name", "collection", "collection_label", "intro", "meal_types", "phases",
        "loads", "dietary", "serves", "prep_minutes", "cook_minutes", "image_url", "min_tier",
        "source", "calories", "carbs_g", "protein_g", "fat_g", "fibre_g", "sort_order", "is_active",
    ]
    ingredient_columns = [
        "recipe_id", "position", "group_label", "food_name", "quantity", "unit", "note",
        "common_food_id", "calories", "carbs_g", "protein_g", "fat_g", "fibre_g",
    ]
    step_columns = ["recipe_id", "position", "body", "timer_seconds"]

    body = _header("VIRRA recipe book — content snapshot")
    body += "delete from public.recipes;\n\n"  # children cascade
    body += insert_statements("public.recipes", recipes, recipe_columns) + "\n"
    body += insert_statements("public.recipe_ingredients", ingredients, ingredient_columns) + "\n"
    body += insert_statements("public.recipe_steps", steps, step_columns) + "\n"
    body += "commit;\n\nnotify pgrst, 'reload schema';\n"

    return _write("recipes.sql", body)


def export_programmes() -> Path:
    exercises = db.select("exercises", order="id")
    programmes = db.select("programmes", order="family,sort_order,id")
    days = db.select("programme_days", order="programme_id,day_index")
    prog_exercises = db.select(
        "programme_exercises", order="programme_day_id,variant,block,section,position"
    )

    exercise_columns = ["id", "name", "description", "load_type", "default_tempo"]
    programme_columns = [
        "id", "family", "family_label", "name", "sport_type", "days_per_week", "duration_weeks",
        "short_description", "full_description", "deload_note", "sort_order", "is_active",
    ]
    day_columns = ["id", "programme_id", "day_index", "focus", "sort_order"]
    pe_columns = [
        "programme_day_id", "variant", "block", "section", "position", "exercise_id",
        "sets", "reps", "tempo", "rest",
    ]

    body = _header("VIRRA strength programmes — content snapshot")
    body += "delete from programmes;\n-- exercises are upserted, never deleted: other content may reference them.\n\n"
    body += (
        insert_statements("exercises", exercises, exercise_columns).rstrip(";\n")
        + "\non conflict (id) do update set\n"
        "  name = excluded.name,\n"
        "  description = excluded.description,\n"
        "  load_type = excluded.load_type,\n"
        "  default_tempo = excluded.default_tempo;\n\n"
    )
    body += insert_statements("programmes", programmes, programme_columns) + "\n"
    body += insert_statements("programme_days", days, day_columns) + "\n"
    body += insert_statements("programme_exercises", prog_exercises, pe_columns) + "\n"
    body += (
        "-- plan_templates rows are DERIVED from programmes by the admin console\n"
        "-- (tools/admin/admin/derive.py) and by migration 20260819010000.\n"
        "-- They are deliberately not snapshotted here; regenerate them instead.\n\n"
    )
    body += "commit;\n\nnotify pgrst, 'reload schema';\n"

    return _write("programmes.sql", body)


def _write(filename: str, body: str) -> Path:
    SEED_DIR.mkdir(parents=True, exist_ok=True)
    path = SEED_DIR / filename
    path.write_text(body, encoding="utf-8")
    return path
