-- Mobility sessions: first load of the authored content. Card 264.
-- GENERATED from mobile/supabase/seed/mobility.json by build-mobility-seed.mjs.
--
-- Safe to run once the 20260913000000_mobility_sessions migration is in.
-- Sessions are upserted by id and each listed session's moves are replaced,
-- so re-running it OVERWRITES any admin-console edit to these 8 sessions.
-- Once Emma is editing them in the console, export from there instead.

begin;

insert into mobility_sessions (id, name, focus, minutes, intensity, phases, is_active, position)
values
  ('wake-up', 'Wake Up', 'Ten minutes to unstick the spine and hips before the day gets going.', 10, 'gentle', array['menstrual','follicular','ovulatory','luteal']::text[], true, 1),
  ('post-run-reset', 'Post-Run Reset', 'Calves, hips and hamstrings straight after a run, before they set.', 10, 'gentle', array['menstrual','follicular','ovulatory','luteal']::text[], true, 2),
  ('wind-down', 'Wind Down', 'Slow floor work and long breaths to settle the body before bed.', 10, 'gentle', array['menstrual','luteal']::text[], true, 3),
  ('hips-and-lower-back', 'Hips and Lower Back', 'Release for the hips and lower back on the days they take the strain.', 20, 'moderate', array['luteal','menstrual']::text[], true, 4),
  ('shoulders-and-upper-back', 'Shoulders and Upper Back', 'Open the chest and free the upper back from desk hours and tight arms.', 20, 'moderate', array['follicular','ovulatory']::text[], true, 5),
  ('full-body-flow', 'Full Body Flow', 'Standing to floor and back again, moving every joint through its range.', 20, 'moderate', array['follicular','ovulatory']::text[], true, 6),
  ('deep-release', 'Deep Release', 'Half an hour of unhurried floor work for the heaviest days.', 30, 'gentle', array['menstrual','luteal']::text[], true, 7),
  ('strong-and-supple', 'Strong and Supple', 'Range of movement with the control to hold it, Pilates style.', 30, 'strong', array['follicular','ovulatory']::text[], true, 8)
on conflict (id) do update set
  name = excluded.name,
  focus = excluded.focus,
  minutes = excluded.minutes,
  intensity = excluded.intensity,
  phases = excluded.phases,
  position = excluded.position;

delete from mobility_session_moves where session_id in ('wake-up', 'post-run-reset', 'wind-down', 'hips-and-lower-back', 'shoulders-and-upper-back', 'full-body-flow', 'deep-release', 'strong-and-supple');

insert into mobility_session_moves (session_id, position, name, description, reps, sets, cue)
values
  ('wake-up', 1, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, 'Let the ribs widen sideways, not the belly.'),
  ('wake-up', 2, 'Pelvic Tilts', 'On your back with knees bent, rock the pelvis to flatten the lower back into the mat, then let it release into a small arch. Keep it small and slow.', '8 slow', null, null),
  ('wake-up', 3, 'Knee Hugs', 'On your back, hug both knees to the chest and rock gently side to side. Let the lower back soften into the mat.', '30s', null, null),
  ('wake-up', 4, 'Supine Twist', 'On your back, drop both knees to one side and turn the head the other way. Let the weight of the legs do the work.', '30s each side', null, null),
  ('wake-up', 5, 'Segmental Bridge', 'On your back, peel the spine off the mat from the tailbone up to a bridge, then lower one vertebra at a time.', '6 slow', null, null),
  ('wake-up', 6, 'Cat Cow', 'On hands and knees, round the spine toward the ceiling on the exhale, then let the chest and tailbone lift on the inhale. Move one vertebra at a time.', '8 slow', null, 'Let the breath set the pace.'),
  ('wake-up', 7, 'Thread the Needle', 'From hands and knees, slide one arm under the other and rest that shoulder on the mat, letting the upper back rotate. Keep the hips still.', '30s each side', null, null),
  ('wake-up', 8, 'Child''s Pose', 'Knees wide, big toes together, sit back toward the heels and reach the arms long. Let the forehead rest and the breath slow.', '5 breaths', null, null),
  ('wake-up', 9, 'Down Dog Pedal', 'In down dog, bend one knee and press the other heel toward the floor, alternating slowly.', '30s', null, null),
  ('wake-up', 10, 'Low Lunge', 'Step one foot forward and lower the back knee to the mat, sinking the hips forward. Keep the front knee over the ankle.', '30s each side', null, null),
  ('wake-up', 11, 'Deep Squat Hold', 'Feet slightly wider than the hips, sink into a full squat with heels down and elbows pressing the knees gently out. Keep the chest lifted.', '30s', null, 'Heels down. Hold something if you need to.'),
  ('wake-up', 12, 'Roll Down', 'Standing tall, nod the chin and roll down the spine one bone at a time until you hang, then restack from the tailbone up.', '4 slow', null, null),
  ('wake-up', 13, 'Shoulder Rolls', 'Stand or sit tall and roll the shoulders up, back and down in slow circles.', '8 each way', null, null),
  ('wake-up', 14, 'Neck Side Stretch', 'Sit tall and lower one ear toward the shoulder, with the opposite arm reaching down. Breathe into the side of the neck.', '20s each side', null, null),
  ('wake-up', 15, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, 'Standing this time. Notice what changed.'),
  ('post-run-reset', 1, 'Calf Stretch on Wall', 'Hands on a wall, step one foot back with the heel down and press it gently to the floor.', '30s each side', null, null),
  ('post-run-reset', 2, 'Standing Hamstring Stretch', 'Rest one heel on a low step and hinge forward from the hips with a flat back. Toes stay pointing up.', '30s each side', null, 'Hinge from the hips. The back stays flat.'),
  ('post-run-reset', 3, 'Half Kneeling Hip Flexor Stretch', 'Kneel on one knee with the other foot forward, tuck the tailbone and shift gently forward until the front of the kneeling hip lengthens.', '30s each side', null, 'Tuck the tailbone first, then shift forward.'),
  ('post-run-reset', 4, 'Half Split', 'From a low lunge, slide the hips back and straighten the front leg, folding over it with a long spine.', '30s each side', null, null),
  ('post-run-reset', 5, 'Down Dog Pedal', 'In down dog, bend one knee and press the other heel toward the floor, alternating slowly.', '30s', null, null),
  ('post-run-reset', 6, 'Pigeon', 'From hands and knees, bring one knee forward behind the wrist with the shin angled across, and fold over it. Keep the hips square.', '45s each side', null, null),
  ('post-run-reset', 7, 'Child''s Pose', 'Knees wide, big toes together, sit back toward the heels and reach the arms long. Let the forehead rest and the breath slow.', '5 breaths', null, null),
  ('post-run-reset', 8, 'Figure Four Stretch', 'On your back, cross one ankle over the opposite knee and draw the legs toward you. Keep the tailbone down.', '30s each side', null, null),
  ('post-run-reset', 9, 'Supine Twist', 'On your back, drop both knees to one side and turn the head the other way. Let the weight of the legs do the work.', '30s each side', null, null),
  ('post-run-reset', 10, 'Knee Hugs', 'On your back, hug both knees to the chest and rock gently side to side. Let the lower back soften into the mat.', '5 breaths', null, null),
  ('wind-down', 1, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '8 breaths', null, 'Make the exhale longer than the inhale.'),
  ('wind-down', 2, 'Pelvic Clocks', 'On your back, picture a clock face on the pelvis and tilt slowly toward each number in turn. The ribs stay heavy the whole way round.', '4 each way', null, null),
  ('wind-down', 3, 'Knee Hugs', 'On your back, hug both knees to the chest and rock gently side to side. Let the lower back soften into the mat.', '30s', null, null),
  ('wind-down', 4, 'Supine Twist', 'On your back, drop both knees to one side and turn the head the other way. Let the weight of the legs do the work.', '45s each side', null, null),
  ('wind-down', 5, 'Figure Four Stretch', 'On your back, cross one ankle over the opposite knee and draw the legs toward you. Keep the tailbone down.', '45s each side', null, null),
  ('wind-down', 6, 'Happy Baby', 'On your back, hold the outside of the feet with knees wide and draw them gently toward the armpits. Keep the tailbone heavy.', '30s', null, null),
  ('wind-down', 7, 'Child''s Pose', 'Knees wide, big toes together, sit back toward the heels and reach the arms long. Let the forehead rest and the breath slow.', '8 breaths', null, null),
  ('wind-down', 8, 'Shell Stretch', 'Kneel and fold forward onto the thighs with the arms by your sides, palms up. Let the back round completely.', '5 breaths', null, null),
  ('wind-down', 9, 'Sphinx', 'Face down with forearms on the mat, lift the chest and let the lower back settle into a gentle arch. Breathe into the front of the body.', '30s', null, 'Nothing forced. Let the lower back settle on its own.'),
  ('wind-down', 10, 'Butterfly', 'Sit with the soles of the feet together and knees open, and fold forward from the hips with a long spine.', '45s', null, null),
  ('wind-down', 11, 'Legs Up the Wall', 'Lie on your back with the legs resting up a wall and the arms open. Let the whole body go heavy.', '1 min', null, 'If there is no wall, rest the calves on a chair.'),
  ('wind-down', 12, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '8 breaths', null, null),
  ('hips-and-lower-back', 1, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, null),
  ('hips-and-lower-back', 2, 'Pelvic Tilts', 'On your back with knees bent, rock the pelvis to flatten the lower back into the mat, then let it release into a small arch. Keep it small and slow.', '8 slow', null, null),
  ('hips-and-lower-back', 3, 'Knee Hugs', 'On your back, hug both knees to the chest and rock gently side to side. Let the lower back soften into the mat.', '30s', null, null),
  ('hips-and-lower-back', 4, 'Figure Four Stretch', 'On your back, cross one ankle over the opposite knee and draw the legs toward you. Keep the tailbone down.', '45s each side', null, null),
  ('hips-and-lower-back', 5, 'Supine Twist', 'On your back, drop both knees to one side and turn the head the other way. Let the weight of the legs do the work.', '45s each side', null, null),
  ('hips-and-lower-back', 6, 'Happy Baby', 'On your back, hold the outside of the feet with knees wide and draw them gently toward the armpits. Keep the tailbone heavy.', '30s', null, null),
  ('hips-and-lower-back', 7, 'Segmental Bridge', 'On your back, peel the spine off the mat from the tailbone up to a bridge, then lower one vertebra at a time.', '8 slow', null, 'One vertebra at a time, up and down.'),
  ('hips-and-lower-back', 8, 'Clam', 'Lie on your side with knees bent and feet together, and lift the top knee without rolling the pelvis back.', '10 each side', null, 'The pelvis stays stacked. Smaller is better.'),
  ('hips-and-lower-back', 9, 'Cat Cow', 'On hands and knees, round the spine toward the ceiling on the exhale, then let the chest and tailbone lift on the inhale. Move one vertebra at a time.', '8 slow', null, null),
  ('hips-and-lower-back', 10, 'Thread the Needle', 'From hands and knees, slide one arm under the other and rest that shoulder on the mat, letting the upper back rotate. Keep the hips still.', '30s each side', null, null),
  ('hips-and-lower-back', 11, 'Child''s Pose', 'Knees wide, big toes together, sit back toward the heels and reach the arms long. Let the forehead rest and the breath slow.', '5 breaths', null, null),
  ('hips-and-lower-back', 12, 'Adductor Rock Back', 'On hands and knees, extend one leg out to the side with the foot flat, and rock the hips back and forward over the kneeling leg.', '8 each side', null, null),
  ('hips-and-lower-back', 13, 'Frog Stretch', 'On hands and knees, widen the knees and turn the feet out, then rock the hips gently back toward the heels.', '45s', null, null),
  ('hips-and-lower-back', 14, '90/90 Hip Switch', 'Sit with one leg bent in front and one behind, both at right angles, and rotate the knees from one side to the other. Stay tall.', '8 slow', null, null),
  ('hips-and-lower-back', 15, '90/90 Forward Fold', 'In the 90/90 seat, hinge the chest forward over the front shin and breathe into the outer hip.', '45s each side', null, null),
  ('hips-and-lower-back', 16, 'Pigeon', 'From hands and knees, bring one knee forward behind the wrist with the shin angled across, and fold over it. Keep the hips square.', '45s each side', null, 'Hips square. A cushion under the hip is fine.'),
  ('hips-and-lower-back', 17, 'Half Kneeling Hip Flexor Stretch', 'Kneel on one knee with the other foot forward, tuck the tailbone and shift gently forward until the front of the kneeling hip lengthens.', '45s each side', null, null),
  ('hips-and-lower-back', 18, 'Lizard', 'From a low lunge, walk the front foot out wide and lower the forearms toward the mat inside the leg.', '45s each side', null, null),
  ('hips-and-lower-back', 19, 'Butterfly', 'Sit with the soles of the feet together and knees open, and fold forward from the hips with a long spine.', '45s', null, null),
  ('hips-and-lower-back', 20, 'Spine Stretch Forward', 'Sit tall with legs straight and hip-width apart, then reach forward over the legs, peeling the spine into a long curve. Draw the belly back as you fold.', '5 slow', null, null),
  ('hips-and-lower-back', 21, 'Saw', 'Sit tall with legs wide and arms out, rotate and reach the little finger past the opposite little toe, then return. Keep both hips heavy.', '5 each side', null, null),
  ('hips-and-lower-back', 22, 'Mermaid', 'Sit with the legs folded to one side, reach the opposite arm overhead and lean over the folded legs, then counter-stretch the other way.', '30s each side', null, null),
  ('hips-and-lower-back', 23, 'Squat & Reach', 'Hold a deep squat and reach one arm overhead, opening through the upper back.', '6 each side', null, null),
  ('hips-and-lower-back', 24, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, null),
  ('shoulders-and-upper-back', 1, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, null),
  ('shoulders-and-upper-back', 2, 'Chin Tucks', 'Sit tall and glide the chin straight back as if making a double chin, lengthening the back of the neck.', '8 slow', null, null),
  ('shoulders-and-upper-back', 3, 'Neck Side Stretch', 'Sit tall and lower one ear toward the shoulder, with the opposite arm reaching down. Breathe into the side of the neck.', '20s each side', null, null),
  ('shoulders-and-upper-back', 4, 'Shoulder Rolls', 'Stand or sit tall and roll the shoulders up, back and down in slow circles.', '8 each way', null, null),
  ('shoulders-and-upper-back', 5, 'Arm Circles', 'Stand tall and circle the arms slowly in both directions, keeping the ribs still.', '8 each way', null, null),
  ('shoulders-and-upper-back', 6, 'Wall Angels', 'Back against a wall with the arms in a goalpost, slide them up and down the wall keeping the wrists and elbows in contact.', '8 slow', null, 'Ribs stay on the wall. Go only as high as that allows.'),
  ('shoulders-and-upper-back', 7, 'Doorway Pec Stretch', 'Forearm on a doorframe at shoulder height, step gently through until the chest opens. Keep the ribs down.', '30s each side', null, null),
  ('shoulders-and-upper-back', 8, 'Chest Opener Hands Clasped', 'Stand tall, clasp the hands behind the back and draw them down and away, lifting the chest.', '30s', null, null),
  ('shoulders-and-upper-back', 9, 'Cat Cow', 'On hands and knees, round the spine toward the ceiling on the exhale, then let the chest and tailbone lift on the inhale. Move one vertebra at a time.', '8 slow', null, null),
  ('shoulders-and-upper-back', 10, 'Thoracic Rotation on All Fours', 'On hands and knees, place one hand behind the head and rotate the elbow toward the ceiling, then down toward the opposite wrist.', '8 each side', null, null),
  ('shoulders-and-upper-back', 11, 'Thread the Needle', 'From hands and knees, slide one arm under the other and rest that shoulder on the mat, letting the upper back rotate. Keep the hips still.', '45s each side', null, null),
  ('shoulders-and-upper-back', 12, 'Scapular Push-ups', 'On hands and knees or in a plank, let the shoulder blades draw together, then push the floor away to spread them. The elbows stay straight.', '10 slow', null, null),
  ('shoulders-and-upper-back', 13, 'Puppy Pose', 'From hands and knees, walk the hands forward and lower the chest toward the mat with the hips high over the knees.', '45s', null, null),
  ('shoulders-and-upper-back', 14, 'Child''s Pose', 'Knees wide, big toes together, sit back toward the heels and reach the arms long. Let the forehead rest and the breath slow.', '5 breaths', null, null),
  ('shoulders-and-upper-back', 15, 'Book Openings', 'Lie on your side with knees bent and arms stacked in front, then lift the top arm and open it behind you like a book, following it with your eyes. Keep the knees pressed together.', '8 each side', null, 'Follow the hand with your eyes. Knees stay glued.'),
  ('shoulders-and-upper-back', 16, 'Prone Y-Raise', 'Face down with arms overhead in a Y, lift the thumbs toward the ceiling and squeeze the lower traps.', '8 slow', null, null),
  ('shoulders-and-upper-back', 17, 'Prone W-Raise', 'Face down with elbows tucked into a W, lift the hands and squeeze the shoulder blades together.', '8 slow', null, null),
  ('shoulders-and-upper-back', 18, 'Prone T-Raise', 'Pull toward the face with elbows high, squeezing the rear shoulders and upper back.', '8 slow', null, null),
  ('shoulders-and-upper-back', 19, 'Swan Prep', 'Lie face down with hands under the shoulders and lift the chest by lengthening the spine forward and up, not by pressing hard. Keep the neck long.', '6 slow', null, 'Length first, height second.'),
  ('shoulders-and-upper-back', 20, 'Swimming Prep', 'Face down, lift the opposite arm and leg a few inches while the belly stays lifted, then swap sides.', '8 each side', null, null),
  ('shoulders-and-upper-back', 21, 'Cobra', 'Face down with hands under the shoulders, press up through the hands to lift the chest while the hips stay on the mat.', '5 breaths', null, null),
  ('shoulders-and-upper-back', 22, 'Shell Stretch', 'Kneel and fold forward onto the thighs with the arms by your sides, palms up. Let the back round completely.', '5 breaths', null, null),
  ('shoulders-and-upper-back', 23, 'Thoracic Extension over Bolster', 'Lie back over a rolled towel or bolster placed under the shoulder blades, hands behind the head, and let the upper back open. Keep the ribs soft.', '1 min', null, null),
  ('shoulders-and-upper-back', 24, 'Spine Twist Seated', 'Sit tall with legs together and arms out, and rotate the ribcage one way and back, growing taller as you turn. The hips stay still.', '6 each side', null, null),
  ('shoulders-and-upper-back', 25, 'Mermaid', 'Sit with the legs folded to one side, reach the opposite arm overhead and lean over the folded legs, then counter-stretch the other way.', '30s each side', null, null),
  ('shoulders-and-upper-back', 26, 'World''s Greatest Stretch', 'Lunge forward, drop the opposite elbow to your instep, then rotate the chest open.', '5 each side', null, null),
  ('shoulders-and-upper-back', 27, 'Roll Down', 'Standing tall, nod the chin and roll down the spine one bone at a time until you hang, then restack from the tailbone up.', '4 slow', null, null),
  ('shoulders-and-upper-back', 28, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, null),
  ('full-body-flow', 1, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, null),
  ('full-body-flow', 2, 'Roll Down', 'Standing tall, nod the chin and roll down the spine one bone at a time until you hang, then restack from the tailbone up.', '4 slow', null, null),
  ('full-body-flow', 3, 'Standing Hip Circles', 'Stand on one leg with a hand on a wall and circle the free knee out and around. Keep the standing hip steady.', '6 each way', null, null),
  ('full-body-flow', 4, 'Leg Swings', 'Holding a wall, swing one leg forward and back from the hip with a relaxed knee. Let the range build over the reps.', '10 each side', null, null),
  ('full-body-flow', 5, 'Deep Squat Hold', 'Feet slightly wider than the hips, sink into a full squat with heels down and elbows pressing the knees gently out. Keep the chest lifted.', '30s', null, null),
  ('full-body-flow', 6, 'Squat & Reach', 'Hold a deep squat and reach one arm overhead, opening through the upper back.', '6 each side', null, null),
  ('full-body-flow', 7, 'World''s Greatest Stretch', 'Lunge forward, drop the opposite elbow to your instep, then rotate the chest open.', '5 each side', null, null),
  ('full-body-flow', 8, 'Cossack Squat', 'Step wide and sink toward one heel with the other leg straight and its toes up, then shift across to the other side.', '6 each side', null, 'Only as low as the heel stays down.'),
  ('full-body-flow', 9, 'Low Lunge Twist', 'In a low lunge, place the opposite hand on the floor and rotate the chest toward the front leg, reaching the free arm up.', '30s each side', null, null),
  ('full-body-flow', 10, 'Lizard', 'From a low lunge, walk the front foot out wide and lower the forearms toward the mat inside the leg.', '30s each side', null, 'Range is easy to find today. Stop where the stretch is clear, not where it ends.'),
  ('full-body-flow', 11, 'Down Dog', 'From hands and knees, lift the hips high into an upside-down V, pressing the chest toward the thighs. Bend the knees as much as you need.', '5 breaths', null, null),
  ('full-body-flow', 12, 'Down Dog Pedal', 'In down dog, bend one knee and press the other heel toward the floor, alternating slowly.', '30s', null, null),
  ('full-body-flow', 13, 'Plank to Down Dog', 'From a plank, push the hips up and back into down dog, then return to plank without the shoulders collapsing.', '6 slow', null, null),
  ('full-body-flow', 14, 'Cat Cow', 'On hands and knees, round the spine toward the ceiling on the exhale, then let the chest and tailbone lift on the inhale. Move one vertebra at a time.', '8 slow', null, null),
  ('full-body-flow', 15, 'Thoracic Rotation on All Fours', 'On hands and knees, place one hand behind the head and rotate the elbow toward the ceiling, then down toward the opposite wrist.', '6 each side', null, null),
  ('full-body-flow', 16, 'Bird Dog', 'On hands and knees, reach the opposite arm and leg long without the hips rotating, then swap.', '6 each side', null, null),
  ('full-body-flow', 17, 'Frog Stretch', 'On hands and knees, widen the knees and turn the feet out, then rock the hips gently back toward the heels.', '30s', null, null),
  ('full-body-flow', 18, 'Pigeon', 'From hands and knees, bring one knee forward behind the wrist with the shin angled across, and fold over it. Keep the hips square.', '45s each side', null, null),
  ('full-body-flow', 19, '90/90 Hip Switch', 'Sit with one leg bent in front and one behind, both at right angles, and rotate the knees from one side to the other. Stay tall.', '8 slow', null, null),
  ('full-body-flow', 20, 'Swan Prep', 'Lie face down with hands under the shoulders and lift the chest by lengthening the spine forward and up, not by pressing hard. Keep the neck long.', '6 slow', null, null),
  ('full-body-flow', 21, 'Child''s Pose', 'Knees wide, big toes together, sit back toward the heels and reach the arms long. Let the forehead rest and the breath slow.', '5 breaths', null, null),
  ('full-body-flow', 22, 'Rolling Like a Ball', 'Sit balanced just behind the tailbone, hold the shins, and roll back to the shoulders and up again without the head touching down. Stay round.', '6', null, 'Stay round. The head never touches down.'),
  ('full-body-flow', 23, 'Spine Stretch Forward', 'Sit tall with legs straight and hip-width apart, then reach forward over the legs, peeling the spine into a long curve. Draw the belly back as you fold.', '5 slow', null, null),
  ('full-body-flow', 24, 'Spine Twist Seated', 'Sit tall with legs together and arms out, and rotate the ribcage one way and back, growing taller as you turn. The hips stay still.', '6 each side', null, null),
  ('full-body-flow', 25, 'Mermaid', 'Sit with the legs folded to one side, reach the opposite arm overhead and lean over the folded legs, then counter-stretch the other way.', '30s each side', null, null),
  ('full-body-flow', 26, 'Segmental Bridge', 'On your back, peel the spine off the mat from the tailbone up to a bridge, then lower one vertebra at a time.', '8 slow', null, null),
  ('full-body-flow', 27, 'Supine Twist', 'On your back, drop both knees to one side and turn the head the other way. Let the weight of the legs do the work.', '30s each side', null, null),
  ('full-body-flow', 28, 'Knee Hugs', 'On your back, hug both knees to the chest and rock gently side to side. Let the lower back soften into the mat.', '30s', null, null),
  ('full-body-flow', 29, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, null),
  ('deep-release', 1, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '8 breaths', null, 'Nothing to do here but breathe.'),
  ('deep-release', 2, 'Pelvic Tilts', 'On your back with knees bent, rock the pelvis to flatten the lower back into the mat, then let it release into a small arch. Keep it small and slow.', '8 slow', null, null),
  ('deep-release', 3, 'Knee Hugs', 'On your back, hug both knees to the chest and rock gently side to side. Let the lower back soften into the mat.', '45s', null, null),
  ('deep-release', 4, 'Figure Four Stretch', 'On your back, cross one ankle over the opposite knee and draw the legs toward you. Keep the tailbone down.', '45s each side', null, null),
  ('deep-release', 5, 'Supine Twist', 'On your back, drop both knees to one side and turn the head the other way. Let the weight of the legs do the work.', '45s each side', null, null),
  ('deep-release', 6, 'Happy Baby', 'On your back, hold the outside of the feet with knees wide and draw them gently toward the armpits. Keep the tailbone heavy.', '45s', null, null),
  ('deep-release', 7, 'Segmental Bridge', 'On your back, peel the spine off the mat from the tailbone up to a bridge, then lower one vertebra at a time.', '6 slow', null, null),
  ('deep-release', 8, 'Side-lying Quad Stretch', 'Lie on your side, hold the top ankle behind you, and gently press the hip forward. Keep the knees in line.', '45s each side', null, null),
  ('deep-release', 9, 'Cat Cow', 'On hands and knees, round the spine toward the ceiling on the exhale, then let the chest and tailbone lift on the inhale. Move one vertebra at a time.', '8 slow', null, null),
  ('deep-release', 10, 'Thread the Needle', 'From hands and knees, slide one arm under the other and rest that shoulder on the mat, letting the upper back rotate. Keep the hips still.', '45s each side', null, null),
  ('deep-release', 11, 'Child''s Pose', 'Knees wide, big toes together, sit back toward the heels and reach the arms long. Let the forehead rest and the breath slow.', '8 breaths', null, null),
  ('deep-release', 12, 'Sphinx', 'Face down with forearms on the mat, lift the chest and let the lower back settle into a gentle arch. Breathe into the front of the body.', '45s', null, null),
  ('deep-release', 13, 'Shell Stretch', 'Kneel and fold forward onto the thighs with the arms by your sides, palms up. Let the back round completely.', '8 breaths', null, null),
  ('deep-release', 14, 'Frog Stretch', 'On hands and knees, widen the knees and turn the feet out, then rock the hips gently back toward the heels.', '45s', null, null),
  ('deep-release', 15, 'Half Kneeling Hip Flexor Stretch', 'Kneel on one knee with the other foot forward, tuck the tailbone and shift gently forward until the front of the kneeling hip lengthens.', '45s each side', null, null),
  ('deep-release', 16, 'Lizard', 'From a low lunge, walk the front foot out wide and lower the forearms toward the mat inside the leg.', '45s each side', null, null),
  ('deep-release', 17, 'Pigeon', 'From hands and knees, bring one knee forward behind the wrist with the shin angled across, and fold over it. Keep the hips square.', '45s each side', null, 'Prop the hip if it needs it. Comfort is the point today.'),
  ('deep-release', 18, '90/90 Forward Fold', 'In the 90/90 seat, hinge the chest forward over the front shin and breathe into the outer hip.', '45s each side', null, null),
  ('deep-release', 19, 'Butterfly', 'Sit with the soles of the feet together and knees open, and fold forward from the hips with a long spine.', '45s', null, null),
  ('deep-release', 20, 'Mermaid', 'Sit with the legs folded to one side, reach the opposite arm overhead and lean over the folded legs, then counter-stretch the other way.', '45s each side', null, null),
  ('deep-release', 21, 'Standing Roll Down with Knee Bend', 'Roll down as before, soften the knees at the bottom so the lower back can let go, then restack from the tailbone.', '4 slow', null, null),
  ('deep-release', 22, 'Calf Stretch on Wall', 'Hands on a wall, step one foot back with the heel down and press it gently to the floor.', '30s each side', null, null),
  ('deep-release', 23, 'Doorway Pec Stretch', 'Forearm on a doorframe at shoulder height, step gently through until the chest opens. Keep the ribs down.', '30s each side', null, null),
  ('deep-release', 24, 'Chest Opener Hands Clasped', 'Stand tall, clasp the hands behind the back and draw them down and away, lifting the chest.', '30s', null, null),
  ('deep-release', 25, 'Neck Side Stretch', 'Sit tall and lower one ear toward the shoulder, with the opposite arm reaching down. Breathe into the side of the neck.', '30s each side', null, null),
  ('deep-release', 26, 'Thoracic Extension over Bolster', 'Lie back over a rolled towel or bolster placed under the shoulder blades, hands behind the head, and let the upper back open. Keep the ribs soft.', '45s', null, null),
  ('deep-release', 27, 'Knee Hugs', 'On your back, hug both knees to the chest and rock gently side to side. Let the lower back soften into the mat.', '30s', null, null),
  ('deep-release', 28, 'Legs Up the Wall', 'Lie on your back with the legs resting up a wall and the arms open. Let the whole body go heavy.', '1 min', null, null),
  ('deep-release', 29, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '10 breaths', null, null),
  ('strong-and-supple', 1, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, null),
  ('strong-and-supple', 2, 'Roll Down', 'Standing tall, nod the chin and roll down the spine one bone at a time until you hang, then restack from the tailbone up.', '4 slow', null, null),
  ('strong-and-supple', 3, 'Standing Single Leg Balance', 'Stand on one leg with the hips level and hold, eyes fixed on one point. Let the foot do the work.', '30s each side', null, null),
  ('strong-and-supple', 4, 'Standing Hip Airplane', 'Hinge over one leg with the other reaching behind, then rotate the pelvis open and closed over the standing hip. Small and controlled.', '5 each side', null, 'Tiny range. The standing knee stays soft.'),
  ('strong-and-supple', 5, 'Deep Squat Hold', 'Feet slightly wider than the hips, sink into a full squat with heels down and elbows pressing the knees gently out. Keep the chest lifted.', '30s', null, null),
  ('strong-and-supple', 6, 'World''s Greatest Stretch', 'Lunge forward, drop the opposite elbow to your instep, then rotate the chest open.', '5 each side', null, null),
  ('strong-and-supple', 7, 'Low Lunge Twist', 'In a low lunge, place the opposite hand on the floor and rotate the chest toward the front leg, reaching the free arm up.', '30s each side', null, null),
  ('strong-and-supple', 8, 'Lizard', 'From a low lunge, walk the front foot out wide and lower the forearms toward the mat inside the leg.', '30s each side', null, 'Range comes easily this week. Stop where the stretch is clear, not where it ends.'),
  ('strong-and-supple', 9, 'Plank to Down Dog', 'From a plank, push the hips up and back into down dog, then return to plank without the shoulders collapsing.', '6 slow', null, null),
  ('strong-and-supple', 10, 'Bird Dog', 'On hands and knees, reach the opposite arm and leg long without the hips rotating, then swap.', '8 each side', null, null),
  ('strong-and-supple', 11, 'Thoracic Rotation on All Fours', 'On hands and knees, place one hand behind the head and rotate the elbow toward the ceiling, then down toward the opposite wrist.', '8 each side', null, null),
  ('strong-and-supple', 12, '90/90 Hip Switch', 'Sit with one leg bent in front and one behind, both at right angles, and rotate the knees from one side to the other. Stay tall.', '8 slow', null, null),
  ('strong-and-supple', 13, 'Pigeon', 'From hands and knees, bring one knee forward behind the wrist with the shin angled across, and fold over it. Keep the hips square.', '45s each side', null, null),
  ('strong-and-supple', 14, 'Hundred Prep', 'On your back, curl the head and shoulders up with the legs in tabletop and pump the arms as you breathe in for five and out for five.', '5 breaths', null, 'In for five, out for five. Ribs stay down.'),
  ('strong-and-supple', 15, 'Single Leg Stretch', 'Curl up, hug one knee in while the other leg reaches long, and switch. The lower back stays on the mat.', '10 each side', null, null),
  ('strong-and-supple', 16, 'Criss Cross', 'Curl up with hands behind the head and rotate the ribcage toward the bent knee as the other leg reaches long.', '10 each side', null, null),
  ('strong-and-supple', 17, 'Dead Bug', 'On your back, extend the opposite arm and leg while pressing the low back into the floor, resisting any twist.', '8 each side', null, null),
  ('strong-and-supple', 18, 'Roll Up', 'Lie long, reach the arms to the ceiling and roll up through the spine to reach for the toes, then roll back down with control.', '6 slow', null, 'Bend the knees if the lower back lifts off.'),
  ('strong-and-supple', 19, 'Spine Stretch Forward', 'Sit tall with legs straight and hip-width apart, then reach forward over the legs, peeling the spine into a long curve. Draw the belly back as you fold.', '5 slow', null, null),
  ('strong-and-supple', 20, 'Saw', 'Sit tall with legs wide and arms out, rotate and reach the little finger past the opposite little toe, then return. Keep both hips heavy.', '5 each side', null, null),
  ('strong-and-supple', 21, 'Teaser Prep', 'Sit balanced on the back of the pelvis with knees bent, reach the arms forward, and extend one leg to match the angle of the other thigh.', '5 each side', null, null),
  ('strong-and-supple', 22, 'Mermaid', 'Sit with the legs folded to one side, reach the opposite arm overhead and lean over the folded legs, then counter-stretch the other way.', '30s each side', null, null),
  ('strong-and-supple', 23, 'Side Kick Series', 'Lie on your side with the top leg hovering and sweep it forward and back without the torso moving.', '10 each side', null, null),
  ('strong-and-supple', 24, 'Clam', 'Lie on your side with knees bent and feet together, and lift the top knee without rolling the pelvis back.', '12 each side', null, null),
  ('strong-and-supple', 25, 'Side Plank', 'Forearm or hand down, lift the hips to make one straight line from head to feet.', '30s each side', null, 'Knee down is a full version, not a lesser one.'),
  ('strong-and-supple', 26, 'Segmental Bridge', 'On your back, peel the spine off the mat from the tailbone up to a bridge, then lower one vertebra at a time.', '8 slow', null, null),
  ('strong-and-supple', 27, 'Shoulder Bridge with Leg Lift', 'Hold a bridge and float one leg toward the ceiling, keeping the hips level, then lower and swap.', '6 each side', null, null),
  ('strong-and-supple', 28, 'Single Leg Circles', 'On your back, reach one leg to the ceiling and draw circles across the body and back around. Keep the pelvis still.', '6 each way, each side', null, null),
  ('strong-and-supple', 29, 'Swan Prep', 'Lie face down with hands under the shoulders and lift the chest by lengthening the spine forward and up, not by pressing hard. Keep the neck long.', '6 slow', null, null),
  ('strong-and-supple', 30, 'Swimming', 'Face down, lift the opposite arm and leg and flutter them in a small quick beat while breathing steadily. The belly stays lifted.', '30s', null, null),
  ('strong-and-supple', 31, 'Cobra', 'Face down with hands under the shoulders, press up through the hands to lift the chest while the hips stay on the mat.', '5 breaths', null, null),
  ('strong-and-supple', 32, 'Child''s Pose', 'Knees wide, big toes together, sit back toward the heels and reach the arms long. Let the forehead rest and the breath slow.', '5 breaths', null, null),
  ('strong-and-supple', 33, 'Thread the Needle', 'From hands and knees, slide one arm under the other and rest that shoulder on the mat, letting the upper back rotate. Keep the hips still.', '30s each side', null, null),
  ('strong-and-supple', 34, 'Supine Twist', 'On your back, drop both knees to one side and turn the head the other way. Let the weight of the legs do the work.', '30s each side', null, null),
  ('strong-and-supple', 35, 'Knee Hugs', 'On your back, hug both knees to the chest and rock gently side to side. Let the lower back soften into the mat.', '30s', null, null),
  ('strong-and-supple', 36, 'Lateral Breathing', 'Lie or sit tall with the hands on the ribs and breathe wide into the sides of the ribcage, letting the belly stay quiet. Exhale fully and feel the ribs knit down.', '5 breaths', null, null);

commit;

notify pgrst, 'reload schema';
