import type { SessionType } from './strengthTypes';

export interface ExerciseDefinition {
  name:           string;
  primaryMuscles: string[];
}

export const EXERCISE_LIBRARY: Record<SessionType | 'general', ExerciseDefinition[]> = {
  lower: [
    { name: 'Romanian Deadlift',     primaryMuscles: ['hamstrings', 'glutes', 'lower back'] },
    { name: 'Hip Thrust',            primaryMuscles: ['glutes', 'hamstrings'] },
    { name: 'Bulgarian Split Squat', primaryMuscles: ['quads', 'glutes', 'hamstrings'] },
    { name: 'Goblet Squat',          primaryMuscles: ['quads', 'glutes', 'core'] },
    { name: 'Sumo Deadlift',         primaryMuscles: ['glutes', 'hamstrings', 'adductors'] },
    { name: 'Box Step-up',           primaryMuscles: ['quads', 'glutes'] },
    { name: 'Reverse Lunge',         primaryMuscles: ['quads', 'glutes', 'hamstrings'] },
    { name: 'Walking Lunge',         primaryMuscles: ['quads', 'glutes', 'hamstrings'] },
    { name: 'Leg Press',             primaryMuscles: ['quads', 'glutes'] },
    { name: 'Leg Extension',         primaryMuscles: ['quads'] },
    { name: 'Hamstring Curl',        primaryMuscles: ['hamstrings'] },
    { name: 'Nordic Curl',           primaryMuscles: ['hamstrings'] },
    { name: 'Glute Bridge',          primaryMuscles: ['glutes', 'hamstrings'] },
    { name: 'Calf Raise',            primaryMuscles: ['calves'] },
    { name: 'Lateral Band Walk',     primaryMuscles: ['glutes', 'hip abductors'] },
    { name: 'Sissy Squat',           primaryMuscles: ['quads'] },
  ],
  upper: [
    { name: 'Dumbbell Row',           primaryMuscles: ['lats', 'rhomboids', 'biceps'] },
    { name: 'Single-arm Row',         primaryMuscles: ['lats', 'rhomboids', 'biceps'] },
    { name: 'Lat Pulldown',           primaryMuscles: ['lats', 'biceps'] },
    { name: 'Seated Cable Row',       primaryMuscles: ['rhomboids', 'lats', 'biceps'] },
    { name: 'Bench Press',            primaryMuscles: ['chest', 'triceps', 'anterior deltoid'] },
    { name: 'Incline Dumbbell Press', primaryMuscles: ['upper chest', 'triceps', 'anterior deltoid'] },
    { name: 'Chest Fly',              primaryMuscles: ['chest', 'anterior deltoid'] },
    { name: 'Overhead Press',         primaryMuscles: ['deltoids', 'triceps', 'upper traps'] },
    { name: 'Arnold Press',           primaryMuscles: ['deltoids', 'triceps'] },
    { name: 'Lateral Raise',          primaryMuscles: ['lateral deltoid'] },
    { name: 'Reverse Fly',            primaryMuscles: ['rear deltoids', 'rhomboids'] },
    { name: 'Face Pull',              primaryMuscles: ['rear deltoids', 'rotator cuff', 'upper traps'] },
    { name: 'Band Pull-apart',        primaryMuscles: ['rear deltoids', 'rhomboids'] },
    { name: 'Bicep Curl',             primaryMuscles: ['biceps'] },
    { name: 'Hammer Curl',            primaryMuscles: ['biceps', 'brachialis'] },
    { name: 'Tricep Extension',       primaryMuscles: ['triceps'] },
    { name: 'Skull Crusher',          primaryMuscles: ['triceps'] },
    { name: 'Push-up',                primaryMuscles: ['chest', 'triceps', 'anterior deltoid'] },
  ],
  strength: [
    { name: 'Deadlift',           primaryMuscles: ['hamstrings', 'glutes', 'lower back', 'traps'] },
    { name: 'Barbell Back Squat', primaryMuscles: ['quads', 'glutes', 'hamstrings', 'core'] },
    { name: 'Front Squat',        primaryMuscles: ['quads', 'glutes', 'core'] },
    { name: 'Pull-up',            primaryMuscles: ['lats', 'biceps', 'core'] },
    { name: 'Dip',                primaryMuscles: ['chest', 'triceps', 'anterior deltoid'] },
    { name: 'Power Clean',        primaryMuscles: ['glutes', 'hamstrings', 'traps', 'core'] },
    { name: 'Hang Clean',         primaryMuscles: ['glutes', 'hamstrings', 'traps'] },
    { name: 'Kettlebell Swing',   primaryMuscles: ['glutes', 'hamstrings', 'core'] },
    { name: "Farmer's Carry",     primaryMuscles: ['forearms', 'traps', 'core'] },
    { name: 'Sled Push',          primaryMuscles: ['quads', 'glutes', 'calves', 'core'] },
    { name: 'Box Jump',           primaryMuscles: ['quads', 'glutes', 'calves'] },
    { name: 'Battle Ropes',       primaryMuscles: ['shoulders', 'core', 'forearms'] },
    { name: 'Turkish Get-up',     primaryMuscles: ['core', 'shoulders', 'glutes'] },
    { name: 'Plank',              primaryMuscles: ['core', 'transverse abdominis'] },
  ],
  general: [
    { name: 'Romanian Deadlift', primaryMuscles: ['hamstrings', 'glutes', 'lower back'] },
    { name: 'Hip Thrust',        primaryMuscles: ['glutes', 'hamstrings'] },
    { name: 'Goblet Squat',      primaryMuscles: ['quads', 'glutes', 'core'] },
    { name: 'Dumbbell Row',      primaryMuscles: ['lats', 'rhomboids', 'biceps'] },
    { name: 'Overhead Press',    primaryMuscles: ['deltoids', 'triceps', 'upper traps'] },
    { name: 'Pull-up',           primaryMuscles: ['lats', 'biceps', 'core'] },
    { name: 'Deadlift',          primaryMuscles: ['hamstrings', 'glutes', 'lower back', 'traps'] },
    { name: 'Plank',             primaryMuscles: ['core', 'transverse abdominis'] },
    { name: 'Kettlebell Swing',  primaryMuscles: ['glutes', 'hamstrings', 'core'] },
  ],
};
